### ISSUE TITLE
about experiment of generalization

### ISSUE THREAD

**Issue by Terminal-K** [PRBonn/MapMOS#15]
hi, thanks for your excellent work! 
may I ask if you have done any preprocessing when testing on apollo or kitti-tracking datasets? since I checked Apollo's LiDAR data and found that its intensity > 1, which seems very inconsistent with the semanticKITTI's training data

**Comment by benemer** [comment]
No, we do not do any pre-processing or modification of parameters. The scans are just converted to the KITTI format and labeled as done in AutoMOS.

And you are absolutely right, that is why both our approaches 4DMOS and MapMOS do not use any additional information except the 3D points. This makes it easier to deploy it in new environments with a different intensity range as it is the case for Apollo.

**Comment by Terminal-K** [comment]
Thanks for your reply!
Do you mean that you only use the spatial coordinates (x, y, z) of each point? Have you compared the performance differences on semanticKITTI before and after adding intensity information?

**Comment by benemer** [comment]
Based on the x,y,z, and time coordinates, we just use the information on which voxels are occupied by points and which are not.

Note that we do not use the coordinate values as features because this can lead to a similar problem when the sensor or its position on the car and therefore the distribution of coordinate values changes.

**Comment by Terminal-K** [comment]
Thanks for your reply, which help me a lot.

Wishing you all the best!
