### ISSUE TITLE
what's the meaning of "mapmos_pipeline --visualize /path/to/weights.ckpt /path/to/data"

### ISSUE THREAD

**Issue by AyanamiHao** [PRBonn/MapMOS#3]
Hello author, I feel that you are such an excellent open source project. But I didn't understand a few problems during the operation according to your instructions (because I'm new to python and I'm not very familiar with python). As the title says, can you give an example to illustrate how this script works, and what are the meanings of the last two parameters? I downloaded the pre-trained model, this compressed file is a .ckpt file, but which one to use as the first parameter after decompression? Does it refer to the file data.pkl? The data folder after decompression of the second parameter "/path/to/data" mapmos.ckpt?
in fact,i have a error problem
File "/home/seu_wx/.conda/envs/torch190/bin/mapmos_pipeline", line 5, in <module>
    from mapmos.cli import app
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 859, in get_code
  File "<frozen importlib._bootstrap_external>", line 916, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/home/seu_wx/star_work/test/MapMOS/src/mapmos/__init__.py'

**Comment by benemer** [comment]
Hey,

You can run `mapmos_pipeline --help` to see how to use the `mapmos_pipeline` executable as explained in the README. The first argument is the path to the weights (`*.ckpt`) file and the second argument `/path/to/data` is be the path to the data, this could be a folder with point cloud files (`*.bin`, `*.pcd`, `*.ply`, `*.bag`, ...) or a single `.bag` rosbag file. This does not work with pickled data (`*.pkl`), because we can not know how to interpret the pickled data. Please convert it to one of the many standardized point cloud data formats first.

Besides that, your error message indicates that the project is not successfully installed. If installed correctly, the output of  `mapmos_pipeline --help`  should look like this:

![image](https://github.com/PRBonn/MapMOS/assets/38326482/747ae895-abd4-4128-9d91-01b4fe795080)

I guess this is because you are using conda. What exactly are the steps that you took to install the project and can you post the output?

You could try installing it via `python -m pip install -v .`, this should use the correct `pip`.

Best
Benedikt
